[2024-08-28T13:47:59.164+0200] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC manual__2024-08-28T11:47:47.173873+00:00 [queued]>
[2024-08-28T13:47:59.170+0200] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskC manual__2024-08-28T11:47:47.173873+00:00 [queued]>
[2024-08-28T13:47:59.170+0200] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T13:47:59.170+0200] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-08-28T13:47:59.171+0200] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T13:47:59.177+0200] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): taskC> on 2024-08-28 11:47:47.173873+00:00
[2024-08-28T13:47:59.184+0200] {standard_task_runner.py:55} INFO - Started process 82341 to run task
[2024-08-28T13:47:59.189+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks', 'taskC', 'manual__2024-08-28T11:47:47.173873+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/multiple_dags.py', '--cfg-path', '/var/folders/q3/lf85n5dd03zdfbv5xqcw4__40000gn/T/tmpx_0fi0cy']
[2024-08-28T13:47:59.191+0200] {standard_task_runner.py:83} INFO - Job 27: Subtask taskC
[2024-08-28T13:47:59.222+0200] {task_command.py:389} INFO - Running <TaskInstance: executing_multiple_tasks.taskC manual__2024-08-28T11:47:47.173873+00:00 [running]> on host roselinas-mbp
[2024-08-28T13:47:59.250+0200] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Roselina_m
AIRFLOW_CTX_DAG_ID=executing_multiple_tasks
AIRFLOW_CTX_TASK_ID=taskC
AIRFLOW_CTX_EXECUTION_DATE=2024-08-28T11:47:47.173873+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-28T11:47:47.173873+00:00
[2024-08-28T13:47:59.250+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/q3/lf85n5dd03zdfbv5xqcw4__40000gn/T
[2024-08-28T13:47:59.251+0200] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130\necho TASK C has ended!']
[2024-08-28T13:47:59.260+0200] {subprocess.py:86} INFO - Output:
[2024-08-28T13:47:59.263+0200] {subprocess.py:93} INFO - TASK C has started!
[2024-08-28T13:48:09.282+0200] {subprocess.py:97} INFO - Command exited with return code 130
[2024-08-28T13:48:09.312+0200] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/roselina/opt/anaconda3/envs/python37/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2024-08-28T13:48:09.319+0200] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=executing_multiple_tasks, task_id=taskC, execution_date=20240828T114747, start_date=20240828T114759, end_date=20240828T114809
[2024-08-28T13:48:09.332+0200] {standard_task_runner.py:105} ERROR - Failed to execute job 27 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 82341)
[2024-08-28T13:48:09.342+0200] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-08-28T13:48:09.357+0200] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
