[2024-08-29T11:29:32.955+0200] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-08-29T09:29:28.012117+00:00 [queued]>
[2024-08-29T11:29:32.962+0200] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-08-29T09:29:28.012117+00:00 [queued]>
[2024-08-29T11:29:32.962+0200] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-08-29T11:29:32.962+0200] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-08-29T11:29:32.962+0200] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-08-29T11:29:32.970+0200] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): insert_values_1> on 2024-08-29 09:29:28.012117+00:00
[2024-08-29T11:29:32.979+0200] {standard_task_runner.py:55} INFO - Started process 159 to run task
[2024-08-29T11:29:32.986+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_1', 'manual__2024-08-29T09:29:28.012117+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/create_sql_pipeline.py', '--cfg-path', '/var/folders/q3/lf85n5dd03zdfbv5xqcw4__40000gn/T/tmptcdmq1uh']
[2024-08-29T11:29:32.990+0200] {standard_task_runner.py:83} INFO - Job 75: Subtask insert_values_1
[2024-08-29T11:29:33.076+0200] {task_command.py:389} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-08-29T09:29:28.012117+00:00 [running]> on host roselinas-mbp
[2024-08-29T11:29:33.106+0200] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Roselina_m
AIRFLOW_CTX_DAG_ID=executing_sql_pipeline
AIRFLOW_CTX_TASK_ID=insert_values_1
AIRFLOW_CTX_EXECUTION_DATE=2024-08-29T09:29:28.012117+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-29T09:29:28.012117+00:00
[2024-08-29T11:29:33.106+0200] {sql.py:254} INFO - Executing: 
            INSERT INTO users (name, age, is_active) VALUES 
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        
[2024-08-29T11:29:33.109+0200] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-08-29T11:29:33.154+0200] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-08-29T11:29:33.154+0200] {sql.py:375} INFO - Running statement: 
            INSERT INTO users (name, age, is_active) VALUES 
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        , parameters: None
[2024-08-29T11:29:33.155+0200] {sql.py:384} INFO - Rows affected: 5
[2024-08-29T11:29:33.158+0200] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_1, execution_date=20240829T092928, start_date=20240829T092932, end_date=20240829T092933
[2024-08-29T11:29:33.184+0200] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-08-29T11:29:33.238+0200] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
