[2024-08-29T11:40:16.298+0200] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-08-29T09:40:12.060611+00:00 [queued]>
[2024-08-29T11:40:16.304+0200] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-08-29T09:40:12.060611+00:00 [queued]>
[2024-08-29T11:40:16.305+0200] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-08-29T11:40:16.305+0200] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-08-29T11:40:16.305+0200] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-08-29T11:40:16.312+0200] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): insert_values_1> on 2024-08-29 09:40:12.060611+00:00
[2024-08-29T11:40:16.320+0200] {standard_task_runner.py:55} INFO - Started process 1183 to run task
[2024-08-29T11:40:16.324+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'executing_sql_pipeline', 'insert_values_1', 'manual__2024-08-29T09:40:12.060611+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/create_sql_pipeline.py', '--cfg-path', '/var/folders/q3/lf85n5dd03zdfbv5xqcw4__40000gn/T/tmp3h56ngnl']
[2024-08-29T11:40:16.349+0200] {standard_task_runner.py:83} INFO - Job 85: Subtask insert_values_1
[2024-08-29T11:40:16.439+0200] {task_command.py:389} INFO - Running <TaskInstance: executing_sql_pipeline.insert_values_1 manual__2024-08-29T09:40:12.060611+00:00 [running]> on host roselinas-mbp
[2024-08-29T11:40:16.472+0200] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Roselina_m
AIRFLOW_CTX_DAG_ID=executing_sql_pipeline
AIRFLOW_CTX_TASK_ID=insert_values_1
AIRFLOW_CTX_EXECUTION_DATE=2024-08-29T09:40:12.060611+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-29T09:40:12.060611+00:00
[2024-08-29T11:40:16.475+0200] {sql.py:254} INFO - Executing: 
            INSERT INTO users (name, age, is_active) VALUES 
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        
[2024-08-29T11:40:16.478+0200] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-08-29T11:40:16.522+0200] {base.py:73} INFO - Using connection ID 'my_sqlite_conn' for task execution.
[2024-08-29T11:40:16.522+0200] {sql.py:375} INFO - Running statement: 
            INSERT INTO users (name, age, is_active) VALUES 
                ('Julie', 30, false),
                ('Peter', 55, true),
                ('Emily', 37, false),
                ('Katrina', 54, false),
                ('Joseph', 27, true);
        , parameters: None
[2024-08-29T11:40:16.523+0200] {sql.py:384} INFO - Rows affected: 5
[2024-08-29T11:40:16.527+0200] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=executing_sql_pipeline, task_id=insert_values_1, execution_date=20240829T094012, start_date=20240829T094016, end_date=20240829T094016
[2024-08-29T11:40:16.541+0200] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-08-29T11:40:16.592+0200] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
